graph TD
    A["Text-Based EcoSystem"] --> B["Project Management<br/>and Collaboration"]
    A --> C["Version control"]
    A --> D["Documentation"]
    A --> E["Programming - Core"]
    A --> F["Programming - accessories"]
    A --> G["Programming - Shell Scripting"]
    
    B --> B1["Github Issues"]
    B --> B2["Jira"]
    
    C --> C1["Git"]
    C --> C2["GitHub"]
    
    D --> D1["Markdown in Github"]
    D --> D2["Flowcharts in<br/>PlantUML"]
    
    E --> E1["VS Code"]
    E --> E2["Miniconda Python<br/>Virtual environments"]
    E --> E3["Github Copilot"]
    E --> E4["Github Actions<br/>for CI/CD and testing"]
    
    F --> F1["VS Code Settings Sync<br/>work env in multiple computers"]
    F --> F2["VS Code Settings<br/>to execute scripts"]
    
    G --> G1["Git Bash<br/>Works in Linux, Windows"]
