version: '3.4'
services:
  python-3:
    build: 
    container_name: python-3
#    image: iotpoc2018.azurecr.io/mole-analytics:${MOLE_APP_VERSION}-amd64
    networks:
      - default
    volumes:
      #For log and WITSML archive files
      - type: bind
        source: C:\Users\achantv\Documents\temp
        target: /opt/app/mole-analytics/log_files
    environment:
      #Connection string will be set using this environment variable
      MOLE_ENV: "iot"
      MOLE_INPUT: "scheduler"

volumes:
  sqlVolume:
networks:
  default:
    external: false
    driver: bridge
