name: assetutilities
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - plotly-express==0.4.1
    - pyyaml
    - pandoc
    - wkhtmltopdf
    # - popplerqt5 Only available in linux systems
    - pdfannots
    - fitz
