name: assetutilities
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - -r requirements.txt  # source pip specific requirements 
#       - -r dev_tools/requirements.txt  # source pip specific requirements 

