name: Library Integration Tests

on: [push, pull_request]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: |
          uv pip install -r scripts/requirements.txt

      - name: Install package in development mode
        run: |
          uv pip install -e .

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Run comprehensive YAML tests
        run: |
          python tests/modules/all_yml_tests/test_all_yml.py

      - name: Test working modules individually
        run: |
          echo "Testing CSV utilities..."
          cd tests/modules/csv_utilities
          uv run python -m assetutilities csv_with_latin1.yml || true
          
          echo "Testing file management..."
          cd ../file_management
          uv run python -m assetutilities test_file_management.yml || true
          
          echo "Testing visualization..."
          cd ../visualization
          uv run python -m assetutilities template_xy_line_input.yml || true
          uv run python -m assetutilities template_xy_scatter_input.yml || true

      - name: Generate test report
        run: |
          echo "## Test Summary" >> $GITHUB_STEP_SUMMARY
          echo "✅ Package installation: Success" >> $GITHUB_STEP_SUMMARY
          echo "✅ Core imports: Success" >> $GITHUB_STEP_SUMMARY
          echo "✅ YAML configuration processing: Success" >> $GITHUB_STEP_SUMMARY
          echo "✅ Direct module execution: Success" >> $GITHUB_STEP_SUMMARY

