name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r dev_tools/requirements.txt

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Test with pytest
        run: |
          pytest src/assetutilities/tests/test_pipeline.py
